#ifndef OMRON_UUIDS_H
#define OMRON_UUIDS_H

#include "esp_gatt_defs.h"

// Services
#define BTSIG_DEV_INFO_SERVICE_UUID      0x180A
#define BTSIG_BATTERY_SERVICE_UUID       0x180F
#define BTSIG_CURR_TIME_SERVICE_UUID     0x1805
#define BTSIG_USER_DATA_SERVICE_UUID     0x181C
#define BTSIG_BLOOD_PRES_SERVICE_UUID    0x1810

// Characteristics
#define OMRON_DIS_SYSTEM_ID_CHAR_R_UUID  0x2A23
#define OMRON_DIS_MODEL_NUM_CHAR_R_UUID  0x2A24
#define OMRON_DIS_SERIAL_NUM_CHAR_R_UUID 0x2A25
#define OMRON_DIS_FW_REV_CHAR_R_UUID     0x2A26
#define OMRON_DIS_HW_REV_CHAR_R_UUID     0x2A27
#define OMRON_DIS_SW_REV_CHAR_R_UUID     0x2A28
#define OMRON_DIS_MANUF_NAME_CHAR_R_UUID 0x2A29
#define OMRON_DIS_CERT_DATA_CHAR_R_UUID  0x2A2A
#define OMRON_BLM_MEAS_CHAR_I_UUID       0x2A35
#define OMRON_BLM_FEAT_CHAR_R_UUID       0x2A49

#endif // OMRON_UUIDS_H
